# Generated by Django 2.0.3 on 2020-02-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AstronomyPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=75)),
                ('explanation', models.TextField()),
                ('url', models.URLField()),
                ('hdurl', models.URLField()),
                ('media_type', models.CharField(max_length=10)),
                ('service_version', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
