# Generated by Django 2.0.3 on 2020-02-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astronomyPicture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronomypicture',
            name='date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='astronomypicture',
            name='explanation',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='astronomypicture',
            name='hdurl',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='astronomypicture',
            name='media_type',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='astronomypicture',
            name='owner',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='astronomypicture',
            name='service_version',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='astronomypicture',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='astronomypicture',
            name='url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
